routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/empresa', 'EmpresaController');
Route::resource('/empleado', 'EmpleadoController');

app/Empleado.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Empleado extends Model
{
  /*
  Setting the table name
  */
  protected $table = 'empleado';

  /*
  Setting the primary key
  */
  protected $primaryKey = 'empleado_id';

  /*
  Setting the primary key
  */
  protected $fillable = ['nombre', 'apellidos', 'empresa_id', 'correo', 'telefono'];

  /*
  * Relation with table empresa.
  */
  public function empresa(){
    return $this->belongsTo('App\Empresa', 'empresa_id');
  }
}

app/Http/Controllers/EmpleadoController.php
<?php

namespace App\Http\Controllers;

use App\Empresa;
use App\Empleado;
use Illuminate\Http\Request;
use App\Http\Requests\EmpleadoRequest;
use Illuminate\Support\Facades\DB;

class EmpleadoController extends Controller
{
  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {
    $empleado = Empleado::paginate(10);
    return view('Empleado/index', ['empleado' => $empleado]);
  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
    $empresa = DB::table('empresa')->get();
    return view('Empleado/create', ['empresa' => $empresa]);
  }

  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(EmpleadoRequest $request)
  {
    Empleado::create($request->all());
    return redirect () -> back () -> with (['status' => 'Empleado creado correctamente.']);
    $validated = $request->validated();
  }

  /**
  * Display the specified resource.
  *
  * @param  \App\Empleado  $empleado
  * @return \Illuminate\Http\Response
  */
  public function show(Empleado $empleado)
  {
    return view('empleado/show', compact('empleado'));
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  \App\Empleado  $empleado
  * @return \Illuminate\Http\Response
  */
  public function edit(Empleado $empleado)
  {
    $empresa = DB::table('empresa')->get();
    return view('empleado/update', compact('empleado', 'empresa'));
  }

  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  \App\Empleado  $empleado
  * @return \Illuminate\Http\Response
  */
  public function update(EmpleadoRequest $request, Empleado $empleado)
  {
    $empleado->update($request->all());
    return redirect () -> back () -> with (['status' => 'Empleado actualizado correctamente.']);
    $validated = $request->validated();
  }

  /**
  * Remove the specified resource from storage.
  *
  * @param  \App\Empleado  $empleado
  * @return \Illuminate\Http\Response
  */
  public function destroy(Empleado $empleado)
  {
    $empleado->delete();
    return redirect () -> back () -> with (['status' => 'Empleado eliminado correctamente.']);
  }
}

resources/views/empleado/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Creación de empleado</div>
                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible" role="alert">
                              <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                                {{ session('status') }}
                            </div>
                        @endif
                        @if (session('fail'))
                            <div class="alert alert-danger alert-dismissible" role="alert">
                              <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                                {{ session('fail') }}
                            </div>
                        @endif
                        <div class="container">
                            <div class="row">
                                <div class="col-12">
                                    @if ($errors->any())
                                        <div class="alert alert-danger alert-dismissible" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>
                                                        {{ $error }}
                                                    </li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif
                                    <form action="{{ route('empleado.store') }}" method="POST" role="form" enctype="multipart/form-data">
                                        @csrf
                                        <div class="form-group row">
                                            <label for="nombre" class="col-md-4 col-form-label text-md-right">Nombres</label>
                                            <div class="col-md-6">
                                                <input type="text" class="form-control" name="nombre" id="nombre">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="apellidos" class="col-md-4 col-form-label text-md-right">Apellidos</label>
                                            <div class="col-md-6">
                                                <input type="text" class="form-control" name="apellidos" id="apellidos">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="empresa_id" class="col-md-4 col-form-label text-md-right">Empresa</label>
                                            <div class="col-md-6">
                                                <select class="form-control" name="empresa_id" id="empresa_id">
                                                  @foreach ($empresa as $emp)
                                                    <option value="{{ $emp->empresa_id }}"> {{ $emp->nombre }} </option>
                                                  @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="correo" class="col-md-4 col-form-label text-md-right">Correo</label>
                                            <div class="col-md-6">
                                                <input type="email" class="form-control" name="correo" id="correo">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="telefono" class="col-md-4 col-form-label text-md-right">Teléfono</label>
                                            <div class="col-md-6">
                                                <input type="text" class="form-control" name="telefono" id="telefono">
                                            </div>
                                        </div>
                                        <div class="form-group row mb-0 mt-5">
                                            <div class="col-md-8 offset-md-4">
                                                <button type="submit" class="btn btn-primary">Guardar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/empleado/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
          <a href="{{ route('empleado.create') }}" class="btn btn-primary" style="margin-bottom: 5px;">Crear nuevo empleado</a>
          <table class="table table-striped">

            <tr>
              <td>ID</td>
              <td>NOMBRE</td>
              <td>APELLIDOS</td>
              <td>EMPRESA</td>
              <td>CORREO</td>
              <td>TELÉFONO</td>
              <td>ACCIONES</td>
            </tr>
            @foreach ($empleado as $emplead)
            <tr>
              <td>{{ $emplead->empleado_id }}</td>
              <td>{{ $emplead->nombre }}</td>
              <td>{{ $emplead->apellidos }}</td>
              <td>{{ $emplead->empresa->nombre}}</td>
              <td>{{ $emplead->correo }}</td>
              <td>{{ $emplead->telefono }}</td>
              <td>
                <a href="{{ route('empleado.show', $emplead->empleado_id) }}" class="btn btn-primary" style="margin-left: 4px;">Ver</a>
                <a href="{{ route('empleado.edit', $emplead->empleado_id) }}" class="btn btn-success">Editar</a>
                <form class="delete" action="{{ route('empleado.destroy', $emplead->empleado_id) }}" method="post" style="float: left;">
                  @csrf
                  @METHOD('DELETE')
                  <button type="submit" class="btn btn-danger" id="dlt" onclick="return confirm('Realmente desea eliminar el empleado?')">Eliminar</button>
                </form>
              </td>
            </tr>
            @endforeach
          </table>
          {{ $empleado->links() }}
          @if (session('status'))
              <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                  {{ session('status') }}
              </div>
          @endif
          @if (session('fail'))
              <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                  {{ session('fail') }}
              </div>
          @endif
        </div>
    </div>
</div>
@endsection

resources/views/empleado/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-md-offset-2">
          <table class="table table-striped">
            <tr>
              <td>ID</td>
              <td>NOMBRE</td>
              <td>APELLIDOS</td>
              <td>EMPRESA</td>
              <td>CORREO</td>
              <td>TELÉFONO</td>
            </tr>
            <tr>
              <td>{{ $empleado->empleado_id }}</td>
              <td>{{ $empleado->nombre }}</td>
              <td>{{ $empleado->apellidos }}</td>
              <td>{{ $empleado->empresa->nombre }}</td>
              <td>{{ $empleado->telefono }}</td>
              <td>{{ $empleado->correo }}</td>
            </tr>
        </table>
        </div>
    </div>
</div>
@endsection

resources/views/empleado/update.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Creación de empleado</div>
                    <div class="card-body">
                      @if (session('status'))
                          <div class="alert alert-success alert-dismissible" role="alert">
                            <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                              {{ session('status') }}
                          </div>
                      @endif
                      @if (session('fail'))
                          <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                              {{ session('fail') }}
                          </div>
                      @endif
                        <div class="container">
                            <div class="row">
                                <div class="col-12">
                                    @if ($errors->any())
                                        <div class="alert alert-danger alert-dismissible" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>
                                                        {{ $error }}
                                                    </li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif
                                    <form action="{{ route('empleado.update', $empleado->empleado_id) }}" method="POST" role="form" enctype="multipart/form-data">
                                        @csrf
                                        @METHOD('PUT')
                                        <div class="form-group row">
                                            <label for="nombre" class="col-md-4 col-form-label text-md-right">Nombres</label>
                                            <div class="col-md-6">
                                                <input type="text" class="form-control" name="nombre" id="nombre" value="{{$empleado->nombre}}">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="apellidos" class="col-md-4 col-form-label text-md-right">Apellidos</label>
                                            <div class="col-md-6">
                                                <input type="text" class="form-control" name="apellidos" id="apellidos" value="{{$empleado->apellidos}}">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="empresa_id" class="col-md-4 col-form-label text-md-right">Empresa</label>
                                            <div class="col-md-6">
                                                <select class="form-control" name="empresa_id" id="empresa_id">
                                                    <option value="{{ $empleado->empresa_id }}" selected> {{ $empleado->empresa->nombre }} </option>
                                                  @foreach ($empresa as $emp)
                                                    <option value="{{ $emp->empresa_id }}"> {{ $emp->nombre }} </option>
                                                  @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="correo" class="col-md-4 col-form-label text-md-right">Correo</label>
                                            <div class="col-md-6">
                                                <input type="email" class="form-control" name="correo" id="correo" value="{{$empleado->correo}}">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="telefono" class="col-md-4 col-form-label text-md-right">Teléfono</label>
                                            <div class="col-md-6">
                                                <input type="text" class="form-control" name="telefono" id="telefono" value="{{$empleado->telefono}}">
                                            </div>
                                        </div>
                                        <div class="form-group row mb-0 mt-5">
                                            <div class="col-md-8 offset-md-4">
                                                <button type="submit" class="btn btn-primary">Guardar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection