routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/empresa', 'EmpresaController');
Route::resource('/empleado', 'EmpleadoController');

app/Empresa.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class Empresa extends Model
{

  /*
  Setting the table name
  */
  protected $table = 'empresa';

  /*
  Setting the primary key
  */
  protected $primaryKey = 'empresa_id';

  /*
  Setting the table columns
  */
  protected $fillable = ['nombre', 'correo', 'logo', 'url'];
}

app/Http/Controllers/EmpresaController.php
<?php

namespace App\Http\Controllers;

use App\Empresa;
use App\Traits\UploadTrait;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\EmpresaRequest;
use Illuminate\Support\Facades\Storage;

class EmpresaController extends Controller
{

  use UploadTrait;

  /**
  * Create a new controller instance.
  *
  * @return void
  */
  public function __construct()
  {
    $this->middleware('auth');
  }

  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {
    $empresa = Empresa::paginate(10);
    return view('empresa/index', ['empresa' => $empresa]);
  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
    return view('empresa/create');
  }

  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(EmpresaRequest $request)
  {
    // Objeto del modelo Empresa
    $empresa = new Empresa;
    // Nombrar la imagen según la empresa
    $name = $request->input('nombre');
    // Establecer la ruta de almacenamiento
    $folder = '/uploads/images/';

    if ($request->file('logo') != null){
      // Establecer fuente de la imagen
      $image = $request->file('logo');
      // Crear la ruta donde irá la imagen renombrada
      $filePath = $folder . $name. '.' . $image->getClientOriginalExtension();
      // Si la imagen carga exitosamente, entonces cree el registro en la base de datos
      if ($this->uploadOne($image, $folder, 'public', $name)){

        $empresa->nombre = $name;
        $empresa->correo = $request->input('correo');
        $empresa->logo = $filePath;
        $empresa->url = $request->input('url');

        if ($empresa->save()){
          return redirect () -> back () -> with (['status' => 'Empresa creada correctamente.']);
        } else{
          Storage::delete($filePath);
          return redirect () -> back () -> with (['fail' => 'Ocurrió un error intentando almacenar la empresa en la base de datos. Contácte al administrador.']);
        }

        $validated = $request->validated();
      } else{
        return redirect () -> back () -> with (['fail' => 'Ocurrió un error almacenando la imagen. Contácte al administrador.']);
      }
    } else{
      $image = 'Nlogo.png';
      // Crear la ruta donde irá la imagen renombrada
      $filePath = $folder . $image;
      $empresa->nombre = $name;
      $empresa->correo = $request->input('correo');
      $empresa->logo = $filePath;
      $empresa->url = $request->input('url');

      if ($empresa->save()){
        return redirect () -> back () -> with (['status' => 'Empresa creada correctamente.']);
      } else{
        Storage::delete($filePath);
        return redirect () -> back () -> with (['fail' => 'Ocurrió un error intentando almacenar la empresa en la base de datos. Contácte al administrador.']);
      }

      $validated = $request->validated();
    }

  }

  /**
  * Display the specified resource.
  *
  * @param  \App\Empresa  $empresa
  * @return \Illuminate\Http\Response
  */
  public function show(Empresa $empresa)
  {
    return view('empresa/show', compact('empresa'));
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  \App\Empresa  $empresa
  * @return \Illuminate\Http\Response
  */
  public function edit(Empresa $empresa)
  {
    return view('empresa/update', compact('empresa'));
  }

  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  \App\Empresa  $empresa
  * @return \Illuminate\Http\Response
  */
  public function update(EmpresaRequest $request, Empresa $empresa)
  {
    $name = $request->input('nombre');
    // Recuperar nombre del logo anterior
    $old_img = $request->input('old_img');

    // Atributos del objeto Empresa
    $pib = array();
    $pib['nombre'] = $name;
    $pib['correo'] = $request->input('correo');
    $pib['url'] = $request->input('url');

    // Si no se cargó una imagen y la empresa no tenía logo
    if($request->file('logo') == null && $request->input('old_img') == '/uploads/images/Nlogo.png'){
      $pib['logo'] = '/uploads/images/Nlogo.png';
      // Si se realiza correctamente la actualización en la base de datos.
      if ($empresa->update($pib)){
        return redirect () -> back () -> with (['status' => 'Empresa actualizada correctamente.']);
        $validated = $request->validated();
      } else{
        return redirect () -> back () -> with (['fail' => 'Ocurrió un error intentando actualizar el registro en la base de datos. Contácte al administrador.']);
      }
    }

    // Si no se cargó una imagen y la empresa tenía logo
    if($request->file('logo') == null && $request->input('old_img') != '/uploads/images/Nlogo.png'){
      $pib['logo'] = $old_img;
      // Si se realiza correctamente la actualización en la base de datos.
      if ($empresa->update($pib)){
        return redirect () -> back () -> with (['status' => 'Empresa actualizada correctamente.']);
        $validated = $request->validated();
      } else{
        return redirect () -> back () -> with (['fail' => 'Ocurrió un error intentando actualizar el registro en la base de datos. Contácte al administrador.']);
      }
    }

    // Si se cargó una imagen y la empresa tenía logo.
    if($request->file('logo') != null && $request->input('old_img') != '/uploads/images/Nlogo.png') {
      //Si se elimina correctamente la imagen anterior, cargue la nueva.
      if (Storage::disk('public')->delete($old_img)){
        // Obtener imagen
        $image = $request->file('logo');
        // Establecer la ruta de almacenamiento
        $folder = '/uploads/images/';
        // Crear la ruta donde irá la imagen renombrada
        $filePath = $folder . $name. '.' . $image->getClientOriginalExtension();
        // Si la imagen carga exitosamente, entonces actualice el registro en la base de datos.
        if($this->uploadOne($image, $folder, 'public', $name)){
          // Asignar nombre con ruta de imagen al atributo logo
          $pib['logo'] = $filePath;
          // Si se realiza correctamente la actualización en la base de datos.
          if ($empresa->update($pib)){
            return redirect () -> back () -> with (['status' => 'Empresa actualizada correctamente.']);
            $validated = $request->validated();
          } else{
            return redirect () -> back () -> with (['fail' => 'Ocurrió un error intentando actualizar el registro en la base de datos. Contácte al administrador.']);
          }
        } else{
          return redirect () -> back () -> with (['fail' => 'Ocurrió un error intentando almacenar el nuevo logo. Contácte al administrador.']);
        }
      } else{
        return redirect () -> back () -> with (['fail' => 'Ocurrió un error intentando eliminar el logo anterior. Contácte al administrador.']);
      }
    }

  }

  /**
  * Remove the specified resource from storage.
  *
  * @param  \App\Empresa  $empresa
  * @return \Illuminate\Http\Response
  */
  public function destroy(Empresa $empresa)
  {
    try {
      if ($empresa->logo != '/uploads/images/Nlogo.png'){
        if ($empresa->delete()){
          if (Storage::disk('public')->delete($empresa->logo)){
            return redirect () -> back () -> with (['status' => 'Empresa eliminada correctamente.']);
          } else{
            return redirect () -> back () -> with (['fail' => 'Ocurrió un error intentando eliminar el logo de la empresa. Contácte al administrador.']);
          }
        } else{
          return redirect () -> back () -> with (['fail' => 'Ocurrió un error intentando eliminar la empresa. Contácte al administrador.']);
        }
      } else {
        if ($empresa->delete()){
          return redirect () -> back () -> with (['status' => 'Empresa eliminada correctamente.']);
        } else{
          return redirect () -> back () -> with (['fail' => 'Ocurrió un error intentando eliminar la empresa. Contácte al administrador.']);
        }
      }
    } catch (Exception $e) {
        return redirect () -> back () -> with (['fail' => 'La empresa no puede ser eliminada debido a que varios empleados siguen vinculados a la misma.']);
        return false;
    }
  }
}

resources/views/empresa/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Creación de empresa</div>
                    <div class="card-body">
                      @if (session('status'))
                          <div class="alert alert-success alert-dismissible" role="alert">
                            <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                              {{ session('status') }}
                          </div>
                      @endif
                      @if (session('fail'))
                          <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                              {{ session('fail') }}
                          </div>
                      @endif
                        <div class="container">
                            <div class="row">
                                <div class="col-12">
                                    @if ($errors->any())
                                        <div class="alert alert-danger alert-dismissible" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>
                                                        {{ $error }}
                                                    </li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif
                                    <form action="{{ route('empresa.store') }}" method="POST" role="form" enctype="multipart/form-data">
                                        @csrf
                                        <div class="form-group row">
                                            <label for="name" class="col-md-4 col-form-label text-md-right">Nombre</label>
                                            <div class="col-md-6">
                                                <input type="text" class="form-control" name="nombre" id="nombre">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="email" class="col-md-4 col-form-label text-md-right">Correo</label>
                                            <div class="col-md-6">
                                                <input type="text" class="form-control" name="correo" id="correo">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="profile_image" class="col-md-4 col-form-label text-md-right">Logo</label>
                                            <div class="col-md-6">
                                                <input type="file" class="form-control" name="logo" id="logo">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="email" class="col-md-4 col-form-label text-md-right">Url</label>
                                            <div class="col-md-6">
                                                <input type="text" class="form-control" name="url" id="url">
                                            </div>
                                        </div>
                                        <div class="form-group row mb-0 mt-5">
                                            <div class="col-md-8 offset-md-4">
                                                <button type="submit" class="btn btn-primary">Guardar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/empresa/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
          <a href="{{ route('empresa.create') }}" class="btn btn-primary" style="margin-bottom: 5px;">Crear nueva empresa</a>
          <table class="table table-striped">
            <tr>
              <td>ID</td>
              <td>NOMBRE</td>
              <td>CORREO</td>
              <td>LOGO</td>
              <td>URL</td>
              <td>ACCIONES</td>
            </tr>
            @foreach ($empresa as $empresas)
            <tr>
              <td>{{ $empresas->empresa_id }}</td>
              <td>{{ $empresas->nombre }}</td>
              <td>{{ $empresas->correo }}</td>
              <td><img src="{{ $empresas->logo }}" alt="100" height="100"></td>
              <td>{{ $empresas->url }}</td>
              <td>
                <a href="{{ route('empresa.show', $empresas->empresa_id) }}" class="btn btn-primary" style="margin-left: 4px;">Ver</a>
                <a href="{{ route('empresa.edit', $empresas->empresa_id) }}" class="btn btn-success">Editar</a>
                <form class="delete" action="{{ route('empresa.destroy', $empresas->empresa_id) }}" method="post" style="float: left;">
                  @csrf
                  @METHOD('DELETE')
                  <button type="submit" class="btn btn-danger" id="dlt" onclick="return confirm('Realmente desea eliminar la empresa?')">Eliminar</button>
                </form>
              </td>
            </tr>
            @endforeach
          </table>
          {{ $empresa->links() }}
          @if (session('status'))
              <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                  {{ session('status') }}
              </div>
          @endif
          @if (session('fail'))
              <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                  {{ session('fail') }}
              </div>
          @endif
        </div>
    </div>
</div>
@endsection

resources/views/empresa/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-md-offset-2">
          <table class="table table-striped">
            <tr>
              <td>ID</td>
              <td>NOMBRE</td>
              <td>CORREO</td>
              <td>LOGO</td>
              <td>URL</td>
            </tr>
            <tr>
              <td>{{ $empresa->id }}</td>
              <td>{{ $empresa->nombre }}</td>
              <td>{{ $empresa->correo }}</td>
              <td><img src="{{ $empresa->logo }}" alt="100" height="100"></td>
              <td>{{ $empresa->url }}</td>
            </tr>
        </table>
        </div>
    </div>
</div>
@endsection

resources/views/empresa/update.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Actualización de empresa</div>
                    <div class="card-body">
                      @if (session('status'))
                          <div class="alert alert-success alert-dismissible" role="alert">
                            <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                              {{ session('status') }}
                          </div>
                      @endif
                      @if (session('fail'))
                          <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                              {{ session('fail') }}
                          </div>
                      @endif
                        <div class="container">
                            <div class="row">
                                <div class="col-12">
                                    @if ($errors->any())
                                        <div class="alert alert-danger alert-dismissible" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>
                                                        {{ $error }}
                                                    </li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif
                                    <form action="{{ route('empresa.update', $empresa->empresa_id) }}" method="POST" role="form" enctype="multipart/form-data">
                                        @csrf
                                        @METHOD('PUT')
                                        <div class="form-group row">
                                            <label for="name" class="col-md-4 col-form-label text-md-right">Nombre</label>
                                            <div class="col-md-6">
                                                <input type="text" class="form-control" name="nombre" id="nombre" value="{{ $empresa->nombre }}">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="email" class="col-md-4 col-form-label text-md-right">Correo</label>
                                            <div class="col-md-6">
                                                <input type="text" class="form-control" name="correo" id="correo" value="{{ $empresa->correo }}">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="profile_image" class="col-md-4 col-form-label text-md-right">Logo</label>
                                            <div class="col-md-1">
                                                <img src="{{ $empresa->logo }}" style="width: 35px; height: 35px;">
                                            </div>
                                            <div class="col-md-5">
                                                <input type="file" class="form-control" name="logo" id="logo">
                                                <input type="text" class="form-control" name="old_img" id="old_img"  style="display: none;" value="{{ $empresa->logo }}">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="email" class="col-md-4 col-form-label text-md-right">Url</label>
                                            <div class="col-md-6">
                                                <input type="text" class="form-control" name="url" id="url" value="{{ $empresa->url }}">
                                            </div>
                                        </div>
                                        <div class="form-group row mb-0 mt-5">
                                            <div class="col-md-8 offset-md-4">
                                                <button type="submit" class="btn btn-primary">Actualizar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection